apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app-with-reverse-proxy
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web-app1
      src: ./web-app1
      ports:
        - name: http
          port: 8080
    - name: web-api
      src: ./api
      ports:
        - name: http
          port: 8081
    - name: web-proxy
      src: ./web-proxy
      ports:
        - name: http
          port: 8082
      publicPort: http
  dnsAppAlias:
    environment: dev
    component: web-proxy
