apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-app-with-reverse-proxy
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web-app1
      src: ./web-app1
      ports:
        - name: http
          port: 8080
    - name: web-app2
      src: ./web-app2
      ports:
        - name: http
          port: 8083
      variables:
        USER_NAME: "John Doe"
      secrets:
        - DB_PASS
    - name: web-api
      src: ./api
      ports:
        - name: http
          port: 8081
    - name: web-proxy
      src: ./web-proxy
      ports:
        - name: http
          port: 8082
      publicPort: http
      authentication:
        oauth2:
          clientId: 7ef841f8-a263-45ea-8993-683cc6817ae2
  dnsAppAlias:
    environment: dev
    component: web-proxy
